@startuml
'https://plantuml.com/class-diagram

class PhoneFactory {
Phone makePhone(String phoneType)
}


interface Phone {
 make()
}

class MiPhone implements Phone {
make()
}

class IPhone implements Phone {
make()
}



PhoneFactory ..|> IPhone
PhoneFactory ..|> MiPhone


@enduml