spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?useSSL=false&allowMultiQueries=true
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
    # 指定数据源类型
#    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8181
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.dao
  configuration:
    map-underscore-to-camel-case: true
