@startuml

skinparam backgroundColor #FFFFFF
skinparam activityBackgroundColor #E6F3FF
skinparam activityBorderColor #003366

start

:Java源代码\n(.java文件);
note right: 左侧编译环境流程

partition "Java编译环境" {
    :Java编译器;
    -> 编译处理;
    :生成字节码\n(.class文件);

}

partition "Java运行期环境" {
    -> bytes;
    :字节码本地\n或网络;
    :java类库;
    repeat
     :类装载器;
    :字节码的验证;

partition jvm{
 fork
        :解释器逐行解释执行;
    fork again
        :即时编译器(JIT)\n编译为机器码;
    end fork

:运行期系统;

}
backward:加载;
repeat while (asm 重新class?)
note right
     根据.class文件的
     组织结构加载生产对应字节码
    end note
}

:操作系统;
:硬件;

end



note right
 解释器逐行解释执行
 包含对Java类库\n(如JavaScript等)\n的调用支持
end note

@enduml